---
kind: pipeline
name: hostapd

platform:
  os: linux
  arch: amd64

steps:
- name: docker_hostapd
  image: plugins/docker
  settings:
    context: ./hostapd
    dockerfile: ./hostapd/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/hostapd
    username:
      from_secret: quay_username

---
kind: pipeline
name: routers

platform:
  os: linux
  arch: amd64

steps:
- name: docker_router_base
  image: plugins/docker
  settings:
    context: ./router_base
    dockerfile: ./router_base/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/router_base
    username:
      from_secret: quay_username

- name: docker_router_openvpn
  image: plugins/docker
  settings:
    context: ./router_openvpn
    dockerfile: ./router_openvpn/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/router_openvpn
    username:
      from_secret: quay_username

---
kind: pipeline
name: cloudflare_dns_proxy

platform:
  os: linux
  arch: amd64

steps:
- name: docker_cloudflare_dns_proxy
  image: plugins/docker
  settings:
    context: ./cloudflare_dns_proxy
    dockerfile: ./cloudflare_dns_proxy/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/cloudflare_dns_proxy
    username:
      from_secret: quay_username

---
kind: pipeline
name: reverse_single

platform:
  os: linux
  arch: amd64

steps:
- name: docker_reverse_single
  image: plugins/docker
  settings:
    context: ./reverse_single
    dockerfile: ./reverse_single/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/reverse_single
    username:
      from_secret: quay_username

---
kind: pipeline
name: tcp_proxy

platform:
  os: linux
  arch: amd64

steps:
- name: docker_tcp_proxy
  image: plugins/docker
  settings:
    context: ./tcp_proxy
    dockerfile: ./tcp_proxy/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/tcp_proxy
    username:
      from_secret: quay_username

...
