pipeline:

  docker_hostapd:
    image: plugins/docker
    repo: jonnrb/hostapd
    context: ./hostapd
    dockerfile: ./hostapd/Dockerfile
    storage_driver: overlay2
    secrets: [ docker_username, docker_password ]

  docker_router_base:
    image: plugins/docker
    repo: jonnrb/router_base
    context: ./router_base
    dockerfile: ./router_base/Dockerfile
    storage_driver: overlay2
    secrets: [ docker_username, docker_password ]

  docker_router_openvpn:
    image: plugins/docker
    repo: jonnrb/router_openvpn
    context: ./router_openvpn
    dockerfile: ./router_openvpn/Dockerfile
    storage_driver: overlay2
    secrets: [ docker_username, docker_password ]
