kind: pipeline
name: hostapd
steps:
- name: docker_hostapd
  image: plugins/docker
  settings:
    repo: jonnrb/hostapd
    context: ./hostapd
    dockerfile: ./hostapd/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: pipeline
name: routers
steps:
- name: docker_router_base
  image: plugins/docker
  settings:
    repo: jonnrb/router_base
    context: ./router_base
    dockerfile: ./router_base/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: docker_router_openvpn
  image: plugins/docker
  settings:
    repo: jonnrb/router_openvpn
    context: ./router_openvpn
    dockerfile: ./router_openvpn/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: pipeline
name: cloudflare_dns_proxy
steps:
- name: docker_cloudflare_dns_proxy
  image: plugins/docker
  settings:
    repo: jonnrb/cloudflare_dns_proxy
    context: ./cloudflare_dns_proxy
    dockerfile: ./cloudflare_dns_proxy/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
