kind: pipeline
name: default

steps:
- name: docker_hostapd
  image: plugins/docker
  settings:
    repo: jonnrb/hostapd
    context: ./hostapd
    dockerfile: ./hostapd/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: docker_router_base
  image: plugins/docker
  settings:
    repo: jonnrb/router_base
    context: ./router_base
    dockerfile: ./router_base/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    debug: true
- name: docker_router_openvpn
  image: plugins/docker
  settings:
    repo: jonnrb/router_openvpn
    context: ./router_openvpn
    dockerfile: ./router_openvpn/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    debug: true
